packaging_format = 2

id = "proxitok"
name = "ProxiTok"
description.en = "Alternative frontend for TikTok"
description.fr = "Frontend alternatif à TikTok"

version = "2.5.0.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://proxitok.herokuapp.com"
demo = "https://proxitok.herokuapp.com/"
code = "https://github.com/pablouser1/ProxiTok"

[integration]
yunohost = ">= 11.2.27"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/pablouser1/ProxiTok/archive/refs/tags/v2.5.0.0.tar.gz"
        sha256 = "c0f23873519ed0cff9eeadeb212a64a672d7a7ab548386ef9b463c75b19fc743"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = ["visitors"]
    api.protected = true

    [resources.apt]
    packages = "php8.3-xml, php8.3-zip, php8.3-redis, php8.3-mbstring, php8.3-curl"
