packaging_format = 2

id = "proxitok"
name = "ProxiTok"
description.en = "Alternative frontend for TikTok"
description.fr = "Frontend alternatif à TikTok"

version = "2.4.9.2~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://proxitok.herokuapp.com"
demo = "https://proxitok.herokuapp.com/"
code = "https://github.com/pablouser1/ProxiTok"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/pablouser1/ProxiTok/archive/refs/tags/v2.4.9.2.tar.gz"
        sha256 = "f39f3d2a720569b4967fb58bf35e08948231deaecc237bf37bae6927b6b69d3c"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = ["visitors"]
    api.protected = true

    [resources.apt]
    packages = "php8.2-xml php8.2-zip php8.2-redis php8.2-mbstring php8.2-curl"
